// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimerParcialLP2.Models;

#nullable disable

namespace PrimerParcialLP2.Migrations
{
    [DbContext(typeof(GestionInventariosContext))]
    partial class GestionInventariosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrimerParcialLP2.Models.Ajuste", b =>
                {
                    b.Property<int>("AjusteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AjusteId"));

                    b.Property<int>("AlmacenId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AjusteId")
                        .HasName("PK__Ajuste__AC5997E00010E8C1");

                    b.HasIndex("AlmacenId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Ajuste", (string)null);
                });

            modelBuilder.Entity("PrimerParcialLP2.Models.Almacen", b =>
                {
                    b.Property<int>("AlmacenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlmacenId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AlmacenId")
                        .HasName("PK__Almacen__022A08768F36B92B");

                    b.ToTable("Almacen", (string)null);
                });

            modelBuilder.Entity("PrimerParcialLP2.Models.Categorium", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoriaId")
                        .HasName("PK__Categori__F353C1E5C4BF2BD1");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("PrimerParcialLP2.Models.Entradum", b =>
                {
                    b.Property<int>("EntradaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntradaId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("EntradaId")
                        .HasName("PK__Entrada__A084667487BC8202");

                    b.HasIndex("ProductoId");

                    b.ToTable("Entrada");
                });

            modelBuilder.Entity("PrimerParcialLP2.Models.Inventario", b =>
                {
                    b.Property<int>("InventarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventarioId"));

                    b.Property<int>("AlmacenId")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("InventarioId")
                        .HasName("PK__Inventar__FB8A24D7E39A7C7B");

                    b.HasIndex("AlmacenId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Inventario", (string)null);
                });

            modelBuilder.Entity("PrimerParcialLP2.Models.Producto", b =>
                {
                    b.Property<int>("ProductoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ProductoId")
                        .HasName("PK__Producto__A430AEA3756A2187");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("PrimerParcialLP2.Models.Proveedor", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProveedorId"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ProveedorId")
                        .HasName("PK__Proveedo__61266A59AE338AB1");

                    b.ToTable("Proveedor", (string)null);
                });

            modelBuilder.Entity("PrimerParcialLP2.Models.Salidum", b =>
                {
                    b.Property<int>("SalidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalidaId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("SalidaId")
                        .HasName("PK__Salida__DC9971633F2E8E97");

                    b.HasIndex("ProductoId");

                    b.ToTable("Salida");
                });

            modelBuilder.Entity("ProductoCategorium", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.HasKey("ProductoId", "CategoriaId")
                        .HasName("PK__Producto__EB0592BD9CE9FAF7");

                    b.HasIndex("CategoriaId");

                    b.ToTable("ProductoCategoria", (string)null);
                });

            modelBuilder.Entity("ProductoProveedor", b =>
                {
                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.HasKey("ProductoId", "ProveedorId")
                        .HasName("PK__Producto__2222C806E660A308");

                    b.HasIndex("ProveedorId");

                    b.ToTable("ProductoProveedor", (string)null);
                });

            modelBuilder.Entity("PrimerParcialLP2.Models.Ajuste", b =>
                {
                    b.HasOne("PrimerParcialLP2.Models.Almacen", "Almacen")
                        .WithMany("Ajustes")
                        .HasForeignKey("AlmacenId")
                        .IsRequired()
                        .HasConstraintName("FK__Ajuste__AlmacenI__32E0915F");

                    b.HasOne("PrimerParcialLP2.Models.Producto", "Producto")
                        .WithMany("Ajustes")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK__Ajuste__Producto__31EC6D26");

                    b.Navigation("Almacen");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PrimerParcialLP2.Models.Entradum", b =>
                {
                    b.HasOne("PrimerParcialLP2.Models.Producto", "Producto")
                        .WithMany("Entrada")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK__Entrada__Product__2C3393D0");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PrimerParcialLP2.Models.Inventario", b =>
                {
                    b.HasOne("PrimerParcialLP2.Models.Almacen", "Almacen")
                        .WithMany("Inventarios")
                        .HasForeignKey("AlmacenId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventari__Almac__36B12243");

                    b.HasOne("PrimerParcialLP2.Models.Producto", "Producto")
                        .WithMany("Inventarios")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK__Inventari__Produ__35BCFE0A");

                    b.Navigation("Almacen");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("PrimerParcialLP2.Models.Salidum", b =>
                {
                    b.HasOne("PrimerParcialLP2.Models.Producto", "Producto")
                        .WithMany("Salida")
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK__Salida__Producto__2F10007B");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ProductoCategorium", b =>
                {
                    b.HasOne("PrimerParcialLP2.Models.Categorium", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK__ProductoC__Categ__3E52440B");

                    b.HasOne("PrimerParcialLP2.Models.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK__ProductoC__Produ__3D5E1FD2");
                });

            modelBuilder.Entity("ProductoProveedor", b =>
                {
                    b.HasOne("PrimerParcialLP2.Models.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .IsRequired()
                        .HasConstraintName("FK__ProductoP__Produ__398D8EEE");

                    b.HasOne("PrimerParcialLP2.Models.Proveedor", null)
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .IsRequired()
                        .HasConstraintName("FK__ProductoP__Prove__3A81B327");
                });

            modelBuilder.Entity("PrimerParcialLP2.Models.Almacen", b =>
                {
                    b.Navigation("Ajustes");

                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("PrimerParcialLP2.Models.Producto", b =>
                {
                    b.Navigation("Ajustes");

                    b.Navigation("Entrada");

                    b.Navigation("Inventarios");

                    b.Navigation("Salida");
                });
#pragma warning restore 612, 618
        }
    }
}
